
CLASSPATH=$CLASSPATH:/usr/share/java/mysql.jar
export CLASSPATH
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
#export HISTCONTROL=ignoredups
export EDITOR=vi

#
# Adding capistrano to path
export PATH=$PATH:/var/lib/gems/1.8/bin/
export PATH=$PATH:/home/yzrider/android/android-sdk-linux_86/tools

#
# Mercurial
export HGUSER="William Keys"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" -a -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color)
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    ;;
*)
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    ;;
esac

# Comment in the above and uncomment this below for a color prompt
#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
alias vi='vim'
alias potter='ssh root@potter.inside'
alias server='ssh root@server1.inside'
alias server2='ssh root@server2.inside'
alias hgcommit='~/Documentation/dev-enviroment/hgcommit.sh'
alias gitcommit='~/Documentation/dev-enviroment/gitcommit.sh'
alias gitclone='~/Documentation/dev-enviroment/gitclone.sh'
alias security3='ssh root@security3.inside'
alias security1='ssh root@security1.inside'
alias term='~/Documentation/dev-enviroment/term.sh'
alias vpn='~/Documentation/dev-enviroment/vpn.sh'
alias networking='cd /media/BILL_DRIVE/college/network-lab'
alias project='cd /media/BILL_DRIVE/college/project'
alias pendrive='cd /media/BILL_DRIVE/college'
alias project='cd /media/BILL_DRIVE/college/project'
alias distributed='cd /media/BILL_DRIVE/college/distributed-systems'
alias software-design='cd /media/BILL_DRIVE/college/software-design'
alias railrails='/var/lib/gems/1.8/bin/rails'

#PRINTER=printername
#export PRINTER

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#fi
